adding new command
eestec-sk/EESTEC-Discord-Bot pull request #3
Opened 2024-03-26 22:55 UTC by hristovskii

2024-03-27 00:02 UTC, NovicaPaunovski requested changes

2024-03-27 00:02 UTC, NovicaPaunovski commented on src/data/currentBoard.ts
> +  `;
Да не го мењаме овај секој пат кога се мења борд, може да направиме на некој начин увек да го зима најновиот? Може да има нешто како hashMap , и тој што е со најголем key (најново додаден) да се увек зема?

2024-03-27 00:02 UTC, NovicaPaunovski commented on src/data/ping.ts
> +  `Оваа команда проверува дали ботот ${userMention('1056972602209484923')} е активен или не.\n
Дали има уопште потреба за оваа команда? Да не додаваме екстра ствари ако нема да се користат

2024-03-27 00:02 UTC, NovicaPaunovski commented on src/components/commands.ts
> +      .setTitle("PING")
Погрешен титл за оваа

2024-03-27 00:03 UTC, hristovskii commented on src/data/ping.ts
> +  `Оваа команда проверува дали ботот ${userMention('1056972602209484923')} е активен или не.\n
Може да се тргне

2024-03-27 00:04 UTC, hristovskii commented on src/components/commands.ts
> +      .setTitle("PING")
Оваа мислам дека цела ќе се тргне така да не е проблем

2024-03-27 00:06 UTC, hristovskii commented on src/data/currentBoard.ts
> +  `;
Според ID? 

Ex.: 
BoardID : 22
Chair: John Doe
PR: John Doe 

И тоа што има најголемо ID тој борд да иде?

2024-03-27 00:09 UTC, NovicaPaunovski commented on src/data/currentBoard.ts
> +  `;
Да, тоа ми беше прво решение што ми падна. Иначе можеш и GPT за совет да прашаш

2024-03-28 15:22 UTC, NovicaPaunovski commented
@hristovskii looks good to me now, ako se soglasuvas mergam

2024-03-28 15:22 UTC, NovicaPaunovski approved these changes

2024-03-28 15:23 UTC, merged